-- MySQL Script generated by MySQL Workbench
-- Tue Apr  1 21:58:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema modelo_db_ex05
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modelo_db_ex05
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelo_db_ex05` DEFAULT CHARACTER SET utf8 ;
USE `modelo_db_ex05` ;

-- -----------------------------------------------------
-- Table `modelo_db_ex05`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_db_ex05`.`fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `razaoSocial` VARCHAR(20) NOT NULL,
  `nomeFantasia` VARCHAR(20) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_db_ex05`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_db_ex05`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(20) NOT NULL,
  `rua` VARCHAR(20) NOT NULL,
  `numero` INT NOT NULL,
  `fone` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(20) NOT NULL,
  `cidade` VARCHAR(20) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_db_ex05`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_db_ex05`.`produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(20) NOT NULL,
  `precoUnitario` DECIMAL(12,2) NOT NULL,
  `idFornecedor` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_fornecedor_produto_idx` (`idFornecedor` ASC),
  CONSTRAINT `fk_fornecedor_produto`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `modelo_db_ex05`.`fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_db_ex05`.`notaFiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_db_ex05`.`notaFiscal` (
  `numeroNota` INT NOT NULL AUTO_INCREMENT,
  `valorNota` DECIMAL(12,2) NOT NULL,
  `dataEmissao` DATE NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`numeroNota`),
  INDEX `fk_cliente_notaFiscal_idx` (`idCliente` ASC),
  CONSTRAINT `fk_cliente_notaFiscal`
    FOREIGN KEY (`idCliente`)
    REFERENCES `modelo_db_ex05`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_db_ex05`.`itemNota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_db_ex05`.`itemNota` (
  `numeroNota` INT NOT NULL,
  `idProduto` INT NOT NULL,
  `qtdItem` INT NOT NULL,
  `valorItem` DECIMAL(12,2) NULL,
  INDEX `fk_notaFiscal_itemNota_idx` (`numeroNota` ASC),
  INDEX `fk_produto_itemNota_idx` (`idProduto` ASC),
  CONSTRAINT `fk_notaFiscal_itemNota`
    FOREIGN KEY (`numeroNota`)
    REFERENCES `modelo_db_ex05`.`notaFiscal` (`numeroNota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_itemNota`
    FOREIGN KEY (`idProduto`)
    REFERENCES `modelo_db_ex05`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

